# Generated by Django 2.2.3 on 2019-07-29 08:50

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_pub',
            field=models.DateField(default=datetime.datetime(2019, 7, 29, 8, 50, 56, 857860, tzinfo=utc), verbose_name=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
